### ISSUE TITLE
Fix test

### ISSUE THREAD

**Issue by murillomamud** [jameswlane/emotion-test-project#1]
https://gist.github.com/murillomamud/e4c88cd9fa1e9e0d0140876e39e0451a

**Comment by jameswlane** [comment]
@murillomamud I fixed the pipeline for https://github.com/jameswlane/react-pure-loaders

You can create a branch and use your fix to fix the skipped test for now.

**Comment by hadermendez** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mhanief, @wcope81, @samet-kum, @syzzo, @Dbanks39, @jianggangjun, @ad5665, @dung-hvt, @matischrodinger, @bebeyoka, @tjarbo, @ftolosa, @phucnguyen81, @tonidezman, @marsovic, @OpaNockback, @arossano, @AlexWilliams2000, @madhank93, @joonjeong, @sizur, @shawnlobo96, @deamonssouls, @JacobPEvans, @Pencroff, @nicolasSchirmer, @farisachugthai, @MartinBucko, @pabloroman, @RainWithDrop, @kenjitagawa, @marktowning, @7agustibm, @DavidCPorter, @cblancasso, @sln-guy, @RoySRobinson, @budayabanu, @valiis, @tmgora, @h1nk, @jacderida, @vrgtms, @jon-anslow, @hanibryant, @FanTomasCZ, @abeyt, @vinaynpp, @yodatak, @mkambecknavmarwaha, @cocka, @pratikbin, @scarletbane, @yutougegeyangzhuchang, @Giancarmine, @tonyma, @alanbort, @EmaLinuxawy, @pc-star, @LiamHoffen, @mah26870, @benghui, @sirBreezy, @techgaun, @greystitch, @QueryLI, @bijiasuo2006, @sxander, @consokodev, @zhoujinfu, @heykamikaze, @rliskunov, @ichcc, @azimuth3d, @rmachuca89, @mygig, @zoumin1516, @jtruchan, @mamadaliev, @gcstang, @Soundarya0, @cnicklaw, @owenfiscus, @wsuff, @fullstackjam, @Tej-Singh-Rana, @arijit9998, @ijanhv, @rdemendoza, @zlefeng, @abelfodil, @wsboyxb, @rcdelfin, @Sathiyarajan, @aUserName123-hue, @fr3lin, @kutzowsky, @emlagowski, @duydoxuanjurrehart, @thiagoalmeidasa, @cscanlin, @anudeepdwaram, @Nepoxx, @thenickstrick, @mikwieczorek, @jlambe, @straes, @tied, @stefan2904, @SuryaElite, @subhead, @dmanifold, @jwojnarowicz, @xiechengsheng, @liweiming0611, @chirangaalwis, @Sefiris, @Akhil325, @ChristianBagley, @tombjerck, @oguzy, @maxgritchin, @nated668, @spelinichenko, @r3wald, @AntonLindman, @ArtemisDicoTiar, @georgetoolit1, @Muiriik, @rajeshg-chopra, @benkrueger, @ShirleyBHU, @diffy0712, @gerxiu, @jimbobaggins420, @lyzenghq, @pavlikovskiy, @cheinigk, @cxqntnt, @jurnlee, @ragetti, @xezpeleta, @johnkaraffa, @Mahdi451, @thejohnha, @rrooij, @paul-k1117, @c88888
